// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/nodeagent/v1/agent.proto

package nodeagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentReporterService_Report_FullMethodName = "/nodeagent.v1.AgentReporterService/Report"
)

// AgentReporterServiceClient is the client API for AgentReporterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentReporterService：节点 agent 向控制面上报数据的统一服务。
type AgentReporterServiceClient interface {
	// Report：统一上报入口。
	// 当前可承载：
	// 1. AgentReport（节点采集快照）
	// 2. heartbeat（节点心跳）
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type agentReporterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentReporterServiceClient(cc grpc.ClientConnInterface) AgentReporterServiceClient {
	return &agentReporterServiceClient{cc}
}

func (c *agentReporterServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, AgentReporterService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentReporterServiceServer is the server API for AgentReporterService service.
// All implementations must embed UnimplementedAgentReporterServiceServer
// for forward compatibility.
//
// AgentReporterService：节点 agent 向控制面上报数据的统一服务。
type AgentReporterServiceServer interface {
	// Report：统一上报入口。
	// 当前可承载：
	// 1. AgentReport（节点采集快照）
	// 2. heartbeat（节点心跳）
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedAgentReporterServiceServer()
}

// UnimplementedAgentReporterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentReporterServiceServer struct{}

func (UnimplementedAgentReporterServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentReporterServiceServer) mustEmbedUnimplementedAgentReporterServiceServer() {}
func (UnimplementedAgentReporterServiceServer) testEmbeddedByValue()                              {}

// UnsafeAgentReporterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentReporterServiceServer will
// result in compilation errors.
type UnsafeAgentReporterServiceServer interface {
	mustEmbedUnimplementedAgentReporterServiceServer()
}

func RegisterAgentReporterServiceServer(s grpc.ServiceRegistrar, srv AgentReporterServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentReporterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentReporterService_ServiceDesc, srv)
}

func _AgentReporterService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentReporterServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentReporterService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentReporterServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentReporterService_ServiceDesc is the grpc.ServiceDesc for AgentReporterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentReporterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeagent.v1.AgentReporterService",
	HandlerType: (*AgentReporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _AgentReporterService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/nodeagent/v1/agent.proto",
}
