// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/nodeagent/v1/agent.proto

package nodeagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportRequest：统一上报请求。
// 当前阶段采用 JSON 透传，便于快速演进 Go 侧结构。
type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload_type:
	// - "agent_report"
	// - "heartbeat"
	PayloadType string `protobuf:"bytes,1,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// JSON 编码后的 payload
	BodyJson string `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	// 内容类型，当前固定 application/json
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// 发送时间（UTC Unix 秒）
	SentAtUnix int64 `protobuf:"varint,4,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	// 节点名，便于服务端快速路由与日志检索
	NodeName      string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_proto_nodeagent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nodeagent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nodeagent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *ReportRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *ReportRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ReportRequest) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *ReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

// ReportResponse：统一上报响应。
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_proto_nodeagent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nodeagent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nodeagent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_nodeagent_v1_agent_proto protoreflect.FileDescriptor

const file_api_proto_nodeagent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/nodeagent/v1/agent.proto\x12\fnodeagent.v1\"\xb1\x01\n" +
	"\rReportRequest\x12!\n" +
	"\fpayload_type\x18\x01 \x01(\tR\vpayloadType\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12 \n" +
	"\fsent_at_unix\x18\x04 \x01(\x03R\n" +
	"sentAtUnix\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\"F\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2[\n" +
	"\x14AgentReporterService\x12C\n" +
	"\x06Report\x12\x1b.nodeagent.v1.ReportRequest\x1a\x1c.nodeagent.v1.ReportResponseB;Z9gpu-scheduler-platform/api/proto/nodeagent/v1;nodeagentv1b\x06proto3"

var (
	file_api_proto_nodeagent_v1_agent_proto_rawDescOnce sync.Once
	file_api_proto_nodeagent_v1_agent_proto_rawDescData []byte
)

func file_api_proto_nodeagent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_proto_nodeagent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_nodeagent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_nodeagent_v1_agent_proto_rawDesc), len(file_api_proto_nodeagent_v1_agent_proto_rawDesc)))
	})
	return file_api_proto_nodeagent_v1_agent_proto_rawDescData
}

var file_api_proto_nodeagent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_nodeagent_v1_agent_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: nodeagent.v1.ReportRequest
	(*ReportResponse)(nil), // 1: nodeagent.v1.ReportResponse
}
var file_api_proto_nodeagent_v1_agent_proto_depIdxs = []int32{
	0, // 0: nodeagent.v1.AgentReporterService.Report:input_type -> nodeagent.v1.ReportRequest
	1, // 1: nodeagent.v1.AgentReporterService.Report:output_type -> nodeagent.v1.ReportResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_nodeagent_v1_agent_proto_init() }
func file_api_proto_nodeagent_v1_agent_proto_init() {
	if File_api_proto_nodeagent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_nodeagent_v1_agent_proto_rawDesc), len(file_api_proto_nodeagent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nodeagent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_nodeagent_v1_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_nodeagent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_proto_nodeagent_v1_agent_proto = out.File
	file_api_proto_nodeagent_v1_agent_proto_goTypes = nil
	file_api_proto_nodeagent_v1_agent_proto_depIdxs = nil
}
