SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS outbox;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS gpu_quotas;
DROP TABLE IF EXISTS bindings;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS allocations;
DROP TABLE IF EXISTS gpu_devices;
DROP TABLE IF EXISTS node_snapshots;
DROP TABLE IF EXISTS gpu_job_events;
DROP TABLE IF EXISTS gpu_jobs;
DROP TABLE IF EXISTS tenants;

SET FOREIGN_KEY_CHECKS = 1;