{{- if .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.existingSecret }}
  namespace: {{ include "gpu-scheduler-platform.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
{{- end }}