{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpu-scheduler-platform.serviceAccountName" . }}
  namespace: {{ include "gpu-scheduler-platform.namespace" . }}
{{- end }}